image: docker:latest

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml

stages:
  - build
  - test

workflow:
  rules: # Run the pipeline only on any commit or on merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH'
      when: always
    - when: never


variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

default:
  before_script:
    - docker info

build-prolog:
  stage: build
  rules: # Run the job only on protected branches
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/aliapr-prolog:latest" ./
    - docker push "$CI_REGISTRY_IMAGE/aliapr-prolog:latest"


test-prolog:
  stage: test
  rules: # Run the job only on any commit or on merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker pull "$CI_REGISTRY_IMAGE/aliapr-prolog:latest"
    - docker run --rm "$CI_REGISTRY_IMAGE/aliapr-prolog:latest"
